### ISSUE TITLE
[Feature Request] Skip SSL Verification on Socket.io

### ISSUE THREAD

**Issue by hikaru150s** [firecamp-io/Firecamp#101]
Will it be possible to add an options to skip SSL Verification especially when trying to connect to a staging/development Socket.io server?

**Comment by pranavwani** [comment]
@hikaru150s Thanks for sharing, disable SSL verification while connecting is possible as mention in the https://github.com/socketio/socket.io/issues/2419 in development phase.

We will add this option soon.

**Comment by Nishchit14** [comment]
[Firecamp v2.0](https://github.com/firecamp-io/Firecamp/releases/tag/v2.0.0) released.
