### ISSUE TITLE
[Feature Request] Auto/Manual refresh GraphQL introspection schema

### ISSUE THREAD

**Issue by ivawzh** [firecamp-io/firecamp#108]
Hi, thanks for developing and maintaining Firecamp. I have tried **EVERY** GraphQL client and you are the best =]

I am doing GraphQL backend development so that the schema is actively changing. Is there a way to refresh the GraphQL introspection doc pannel?

**Comment by Nishchit14** [comment]
Thank you @ivawzh for asking this feature, for now, if you hit enter in URL bar then It'll refresh the introspection schema.

We're designing v2 for GraphQL PLayground and we have included this feature with better accessibility.  I'll keep you updated here with it's progress.

**Comment by pranavwani** [comment]
@ivawzh feature has been shipped with the earlier version. feel free to reopen the issue
