### ISSUE TITLE
[Feature Request] Listen to all Socket.io events

### ISSUE THREAD

**Issue by hmenzagh** [firecamp-io/firecamp#110]
It would be great for fast development and debugging to have an option to show all socket.io events. This could be achieved with something like [socketio-wildcard](https://github.com/hden/socketio-wildcard) or a similar implementation.

Thanks for the great work btw !

**Comment by Nishchit14** [comment]
@hmenzagh Thanks for this FR, It seems like this is possible with extension/plugin like system. we're planning for it so a user can extend the functionality through extension in Firecamp.

**Comment by waffln** [comment]
It would be very cool if there was wildcard / asterisk support which would then listen to all events.

**Comment by Nishchit14** [comment]
shipped with [v2.4.0](https://github.com/firecamp-io/firecamp-oss/releases/tag/v2.4.0)
