### ISSUE TITLE
Feature Improvement - Multi Edit in header and body parameters

### ISSUE THREAD

**Issue by dhruten** [firecamp-io/firecamp#112]
Currently we can not edit multiple parameters in header or body, just like in a text editor. Adding each parameter individually makes it tedious task. Thus it would be better if we can get an a minor improvement in parameter add and update actions.

**Comment by pranavwani** [comment]
shipped with [v2.5.0](https://github.com/firecamp-io/firecamp/releases/tag/v2.5.0)
