### ISSUE TITLE
MacOS Menu Bar Icon

### ISSUE THREAD

**Issue by TokenChingy** [firecamp-io/Firecamp#114]
The menu bar icon on MacOS 10.15.5 is showing as overtly large. It looks very well out of place. On top of that, maybe include the ability to use a dark icon for light theme and a light icon for dark theme?

![Screenshot](https://i.imgur.com/wtBcFIe.png)

**Comment by Nishchit14** [comment]
This is awesome feedback!! Thanks @TokenChingy

**Comment by Nishchit14** [comment]
[Firecamp v2.0](https://github.com/firecamp-io/Firecamp/releases/tag/v2.0.0) released.
