### ISSUE TITLE
Tab width not resizable 

### ISSUE THREAD

**Issue by sebastian-brunner** [firecamp-io/firecamp#122]
The tab width for graphql collections are not resizable. Thus, for meaningful names the control icons for deleting, loading or executing a graphql query/mutation are hidden in the widget on the right and cannot be accessed any more.

1. Creat new graphql tab
2. Enter a query/mutation with a long name
3. Click "Push to collection"
4. Try to click the "delete", "load" or "run" icon for the saved qraphql instance

Platform infromation:
 - Type:  Desktop and Chrome Extension
 - OS: Linux
 - Firecamp Version: v1.4.4

**Comment by Nishchit14** [comment]
Thank you @sebastian-brunner for driving the attention. 🙌  We'll improve the accessibility here and release it soon in the next release.

**Comment by pranavwani** [comment]
@sebastian-brunner thanks for raising the issue. 

The issue is fixed and shipped with [v2.5.0](https://github.com/firecamp-io/firecamp/releases/tag/v2.5.0)
