### ISSUE TITLE
[Socket.io] [RE Use-Case] Unable to use the polling transport, and websocket just quickly disconnects

### ISSUE THREAD

**Issue by MasicoreLord** [firecamp-io/Firecamp#126]
**Describe the bug**
While attempting to establish a connection to a service's socket.io, I got errors like xhr polling error (which internally was an unknown transport), and for websocket, no output in devtools network tab, and just quick disconnect.

**To Reproduce**
Since there's no cookie setting support yet as referenced in #120, you are going to have to open devtools (which was ctrl+shift+3 in my case on linux)
* Enter into console:
`window.location.href = "https://www.guilded.gg"`
* Copy cookies for that domain from a browser already logged in
* Set the Expiration to some date in the future, or the same ones you got from copying in the browser, so they don't go away
* Type: `history.back()` or restart firecamp
* Set query strings as follows

![image](https://user-images.githubusercontent.com/11468845/89104700-48c60880-d3e9-11ea-8c5b-7d68c3ffb137.png)
(ignore bottom bit, the browser embedded in that tool won't let you define those headers, they are unticked, so they don't do anything)
* Try reproduction w/ polling and websockets, and w/ just websockets ticked

**Expected behavior**
I expect both to work fine w/o errors and let me establish a connection

**Screenshots 0r Video**
* W/ websockets only (it just drops the connection quick as you can see), there were some attempts mixed in w/ polling enabled to (that was the xhr polling errors)
*no output in network tab for it*

![quickly disconnects w/ websockets](https://cdn.discordapp.com/attachments/738236503750213744/739128921722978304/unknown.png)

* W/ polling

![unknown transport and xhr polling error when polling is enabled](https://cdn.discordapp.com/attachments/738236503750213744/739131131496235018/unknown.png)

**Platform (please complete the following information):**
 - Type:  Desktop
 - OS: Linux
 - Firecamp Version: v1.4.4

**Comment by Nishchit14** [comment]
@MasicoreLord Thanks for sharing this case, It seems CORS issue at first glance. Can you please allow CORS policy with `*` and then try?

**Comment by ketanISM** [comment]
Hi, I am getting the exact same issue in Firecamp v2.0.0-rc-1.

v 1.4.7 it is connected.
![image](https://user-images.githubusercontent.com/6535591/100107696-f032e380-2e8f-11eb-8665-94b582d190e1.png)

v v2.0.0-rc-1 It disconnects and tries to reconnect and again disconnect.
![image](https://user-images.githubusercontent.com/6535591/100107871-240e0900-2e90-11eb-8566-cae670f52ee3.png)

**Comment by Nishchit14** [comment]
@ketanISM, Thanks for sharing the case, would you like to connect over screen share? if yes then please send me DM in discord. I'm curious to understand your use-case.

**Comment by awesomelike** [comment]
This error happened to me with the socket.io@3.1.0 on my server.
Then I downgraded it to version 2.4.0. 
Now everything works fine :)

**Comment by Nishchit14** [comment]
@awesomelike It's because Firecamp supports `SocketIO v2.x.x` at this moment, we're building support for `SocketIO v3`. It'll be available soon in `Firecamp v2`. stay tuned here https://discord.gg/8hRaqhK

**Comment by bayareacoder** [comment]
is there a version now that supports socket.io v3? I stumbled upon this thread since Firecamp doesn't connect for me. If it doesn't support a default latest version of a spec it should be clearly stated in the docs.

**Comment by Nishchit14** [comment]
@bayareacoder  The SocketIOv3 support is now released in the canary version 🚀. You can download them from the below links.
[Linux](https://firecamp.netlify.app/.netlify/functions/download?env=canary&pt=lin), [Mac](https://firecamp.netlify.app/.netlify/functions/download?env=canary&pt=mac), [Win](https://firecamp.netlify.app/.netlify/functions/download?env=canary&pt=win)

cc @awesomelike @ketanISM @MasicoreLord

**Comment by Nishchit14** [comment]
shiped with [v2.0.](https://github.com/firecamp-io/Firecamp/releases/tag/v2.0.0)
