### ISSUE TITLE
Camel case headers are changed to small case

### ISSUE THREAD

**Issue by arunkumaranand** [firecamp-io/firecamp#128]
**Describe the bug**
Headers those are in camel cases are converted as small case in request in GraphQL playground.

**To Reproduce**
1. Go to GraphQL Playground and create your request
2. Go to Header section and a new custom Header "customerType" with any value
3. Click on 'Send' Request
4. Go to 'Timeline' view in Response section
5. Observe the Header keys are converted to small cases (ie. "customerType" -> "customertype")

**Expected behavior**
Expected to retain the same case as entered in the request to the server

**Screenshots 0r Video**
![image](https://user-images.githubusercontent.com/10808063/89876526-67dc4b80-dbdc-11ea-88ef-8bf571a2c2c7.png)

**Platform (please complete the following information):**
 - Type:  Desktop
 - OS: Windows
 - Firecamp Version: v1.4.4

**Additional context**

**Comment by pranavwani** [comment]
According to [RFC 7540](https://tools.ietf.org/html/rfc7540#section-8.1.2) 

> header field names MUST be converted to lowercase prior to their
   encoding in HTTP/2.  A request or response containing uppercase
   header field names MUST be treated as malformed

As currently all the HTTP and GraphQL clients request send via HTTP/2. It can be sent via selecting different versions from the config tab in the upcoming version of the Firecamp.

**Comment by pranavwani** [comment]
@arunkumaranand closing as not an issue. Please select the `v1_1` from the HTTP request config tab which allows passing case-sensitive headers.
