### ISSUE TITLE
WS - Response UI get disturb.

### ISSUE THREAD

**Issue by shreya-gr** [firecamp-io/Firecamp#129]
**Describe the bug**
in WS of Firecamp client, while using JSON as the message req payload, response UI get's disturbed and overlapped. Send and receiving messages both get overlapped. 

**To Reproduce**
1. URL `wss://api.crosstower.com/api/2/ws`
2. JSON request message payload JSON `{
  "method": "getSymbol",
  "params": {
    "symbol": "ETHBTC"
  },
  "id": 123
}`
3. Click on the Send button. 
4. Observe the Response.

**Expected behavior**
Due to overlap, sending messages can't scroll, copy. 

**Screenshots 0r Video**
![Screen Shot 2020-08-14 at 10 38 40 AM](https://user-images.githubusercontent.com/21064733/90216063-2dacbd00-de1b-11ea-807b-70fba1b8b099.png)

**Platform (please complete the following information):**
 - Type:  or 
 - OS: Mac OS 
 - Firecamp Version: [ eg v1.4.4 ]

**Additional context**

**Comment by shreya-gr** [comment]
Receiving messages must be in clear JSON Style. 
ie. JSON 
``` {
  "jsonrpc": "2.0",
  "result": {
    "id": "ETHBTC",
    "baseCurrency": "ETH",
    "quoteCurrency": "BTC",
    "quantityIncrement": "0.001",
    "tickSize": "0.000001",
    "takeLiquidityRate": "0.001",
    "provideLiquidityRate": "-0.0001",
    "feeCurrency": "BTC"
  },
  "id": 123
}```

**Comment by Nishchit14** [comment]
[Firecamp v2.0](https://github.com/firecamp-io/Firecamp/releases/tag/v2.0.0) released.
