### ISSUE TITLE
Auto-connect Attempts

### ISSUE THREAD

**Issue by iGoodie** [firecamp-io/Firecamp#13]
As far as I observed, the app tries to reconnect after the connection is closed by the server.
I have to force shutdown my server software very often, while testing it.
I would really appreciate auto-connect option to be an user input instead of a hardcoded thing :D

**Comment by Nishchit14** [comment]
That's a great use-case, thanks @iGoodie 

We'll add this `reconnect` option in config soon.

**Comment by iGoodie** [comment]
Thanks a lot! I will be looking forward 👍
