### ISSUE TITLE
[Feature Request] Support Socket IO 3.0.0

### ISSUE THREAD

**Issue by dschonhardt** [firecamp-io/Firecamp#136]
After upgrading our app to Socket.IO v3 firecamp is unable to connect.  Would be awesome to add support for the latest socketIO version.

**Comment by Nishchit14** [comment]
@dschonhardt That would be a great support. Thank you for asking. We'll surely consider it soon.

**Comment by Divlo** [comment]
It would be great to have the support for `socket.io@3.0.0`! @Nishchit14 
Any news ?
Firecamp is not an open source project ?  
We could improve together the project and open a PR to add the support for socket.io 3.0.0.

**Comment by Nishchit14** [comment]
Thank you for asking it @Divlo, We're still working on v3 support, You can expect it in 3-4weeks in canary. and Firecamp is not oss yet, but we're willing to do it soon.

**Comment by Hesamp** [comment]
Hi, we still waiting for socket.io v3

**Comment by Nishchit14** [comment]
SocketIO v3 support has been released under the **Firecamp canary v2.0.1-RC-3** version. It's privately available for now so please join the [Firecamp Discord Server](https://discord.gg/8hRaqhK) and send me a DM. I'll share the download link immediately. 

@Divlo @Hesamp @dschonhardt thanks for asking it here.

**Comment by Nishchit14** [comment]
[Firecamp v2.0](https://github.com/firecamp-io/Firecamp/releases/tag/v2.0.0) released.
