### ISSUE TITLE
Variable is not sent

### ISSUE THREAD

**Issue by pavelsaman** [firecamp-io/firecamp#139]
**Describe the bug**

For the following query, variable is not sent, therefore the default argument value is used, which returns much more results than I want.

**To Reproduce**
1. Issue a GraphQL request with Ctrl + Enter shortcut to https://demagog.cz/graphql:
```
query FilterSpeakers($limit: Int) {
  speakers(limit: $limit) {
    id
  }
}
```
and variables:
```
{
  "limit": 7
}
```
2. See that `limit` variable was not sent:
![image](https://user-images.githubusercontent.com/24702416/102393156-49e28580-3fd8-11eb-9a6e-9d55c34d1387.png)

I've tried with different clients like GraphiQL:
![image](https://user-images.githubusercontent.com/24702416/102393047-24ee1280-3fd8-11eb-9638-5fd452a05b52.png)

or Altair:
![image](https://user-images.githubusercontent.com/24702416/102392952-09830780-3fd8-11eb-9920-52e30eb65ecc.png)

If I use the refresh button, or Send button, it seems the variable is set and send correctly, it just doesn't work with Ctrl + Enter. I initially didn't notice this, but now I do. I still consider it a bug, but perhaps there's some logic behind it that only I'm not aware of. However, I use shortcuts often, so I'd vote for the same behaviour even then I press Ctrl + Enter to send a request.

**Expected behavior**

Setting and sending defined variables with correct values.

**Platform:**
 - Type:  desktop, installed via snap
 - OS: Manjaro 20.2
 - Firecamp Version: v1.4.4

**Comment by Nishchit14** [comment]
it seems like this issue has been resolved already or happening in the special cases as we've passed many releases then after. I am unable to reproduce the same with the latest version v2.2.1

**Comment by pranavwani** [comment]
@pavelsaman issue fixed and shipped with the earlier version. feel free to reopen if facing again

**Comment by meenabassem** [comment]
I can confirm the issue exists on 

- M1 Macbook Pro 2021
- MacOS Ventura 13.1
- Firecasmp 2.6.1 (latest installed via homebrew)

**Comment by Nishchit14** [comment]
Thank you @meenabassem for confirming. This issue has been fixed in the[ chrome extension](https://chrome.google.com/webstore/detail/firecamp-a-multi-protocol/eajaahbjpnhghjcdaclbkeamlkepinbl) I guess if you want to try it.

We're about to launch the major version v3, It'll have this fixed soon.

**Comment by meenabassem** [comment]
> Thank you @meenabassem for confirming. This issue has been fixed in the[ chrome extension](https://chrome.google.com/webstore/detail/firecamp-a-multi-protocol/eajaahbjpnhghjcdaclbkeamlkepinbl) I guess if you want to try it.
> 
> We're about to launch the major version v3, It'll have this fixed soon.

Great, Thanks for the update, will use the extension for now and wait for the update
