### ISSUE TITLE
Yaml is not recognised in response body

### ISSUE THREAD

**Issue by pavelsaman** [firecamp-io/Firecamp#142]
**Describe the bug**

Yaml is not recognised and pretty-printed when such a response body arrives.

**To Reproduce**

1. Get a REST API response where data are sent back in yaml format, e.g. this endpoint: `https://randomuser.me/api/?results=1&format=yaml`
2. Yaml is not recognised and such a response body is not pretty-printed:

![image](https://user-images.githubusercontent.com/24702416/103007782-50bb4c00-4534-11eb-97ed-4ee1c132bee0.png)

**Expected behavior**

Some other major data formats like json, xml are always by default pretty-printed, e.g.:

![image](https://user-images.githubusercontent.com/24702416/103007890-806a5400-4534-11eb-9541-4212018df504.png)

**Platform (please complete the following information):**
 - Type: desktop, snap install
 - OS: Manjaro 20.2
 - Firecamp Version: v1.4.4

**Comment by Nishchit14** [comment]
released https://github.com/firecamp-io/Firecamp/releases/tag/v2.0.11
