### ISSUE TITLE
ArrayBuffer data is sent up as the ascii equivalent string instead of the actual binary data

### ISSUE THREAD

**Issue by chris-schmitz** [firecamp-io/Firecamp#143]
**Describe the bug**
I'm trying to send an ArrayBuffer up to my server, but the data that ends up isn't the actual binary data, it's the ascii ascii character equivalent of the binary data. i.e. if I tried to send up `00000001`, it would be sent up as a string. The actual data going up would be `0x30 0x30 0x30 0x30 0x30 0x30 0x30 0x31` since `0x30` is the ascii equivalent of the character `0`  and `0x31` is the string character of `1`. 

TBH I could be using the tool wrong. I couldn't find a definitive explanation of how to send the ArrayBuffer, so I'm assuming I just provide the raw data. 

**To Reproduce**
1. Start a websocket server
2. Point firecamp at the server and connect
3. Change the message type to an ArrayBuffer of any size
4. Send the message
5. On the server, dump the message and look at the hex values in the buffer, they'll be for the ascii codes and not the actual binary information sent 

**Expected behavior**
I'd expect the data being sent up to be the binary data from the buffer. 

**Screenshots 0r Video**
![sending binary array1](https://user-images.githubusercontent.com/2437424/103048409-27aab380-4554-11eb-857b-5c2c4a08a6df.gif)
[_smoother vid version of the recording can be found here_](https://vimeo.com/494286299)

**Platform (please complete the following information):**
 - Type:  Desktop
 - OS: Mac OS 11.0.1
 - Firecamp Version: v1.4.4

**Comment by Nishchit14** [comment]
@chris-schmitz Have you tried the following snippets at your WS server?

```js
ws.binaryType = "arraybuffer"
ws.on('message', data => {
  console.log(data);
})
```

Here is the [API reference](https://github.com/websockets/ws/blob/HEAD/doc/ws.md#websocketbinarytype)

**Comment by chris-schmitz** [comment]
I tried adding that setting but I'm still seeing utf encoded values.

<img width="1618" alt="Screen Shot 2020-12-26 at 8 17 34 AM" src="https://user-images.githubusercontent.com/2437424/103153027-f0eebc00-4752-11eb-81d1-faa5e0cdca04.png">

That said, I didn't read the linked issue in depth yet, I'll review that more and see if it has more detail that I can dig into.

**Comment by Nishchit14** [comment]
@chris-schmitz Can you please confirm this issue? It's been shipped under the `Canary v2 RC-8` release. If you think anything can still be improved then please let us know :)

**Comment by Nishchit14** [comment]
[Firecamp v2.0](https://github.com/firecamp-io/Firecamp/releases/tag/v2.0.0) released.
