### ISSUE TITLE
Postman collection v2.1 incorrectly imported into Firecamp

### ISSUE THREAD

**Issue by pavelsaman** [firecamp-io/Firecamp#146]
**Describe the bug**

Incorrect import of a collection v2.1 from Postman to Firecamp.

**To Reproduce**
1. Import this Postman collection into Firecamp (it's a JSON format, I just renamed the file to end with .txt because .json is not supported here)
[Hyperinzerce.postman_collection.txt](https://github.com/firecampapp/Firecamp/files/5770801/Hyperinzerce.postman_collection.txt)

2. Drop it into import zone in Firecamp
3. See what requests have been imported, there're some missing, e.g. in ads folder:

![image](https://user-images.githubusercontent.com/24702416/103660092-7ea98300-4f6d-11eb-8aff-a97b5ccd9c47.png)

**Expected behavior**
Import all requests form the Postman collection.

**Screenshots 0r Video**

![image](https://user-images.githubusercontent.com/24702416/103660107-849f6400-4f6d-11eb-9e89-f863fba9d0d6.png)

And this is how I exported the collection from Postman, it's in their v2.1 format:

![image](https://user-images.githubusercontent.com/24702416/103660158-92ed8000-4f6d-11eb-9076-e4d7566918da.png)

**Platform (please complete the following information):**
 - Type:  desktop
 - OS: Windows
 - Firecamp Version: v1.4.7

**Comment by Nishchit14** [comment]
Thank you for driving the attention @pavelsaman , we're on it to fix.

**Comment by Nishchit14** [comment]
[Firecamp v2.0](https://github.com/firecamp-io/Firecamp/releases/tag/v2.0.0) released.
