### ISSUE TITLE
[Feature Request] Add beautify and minify option for structured data like json, yaml etc both in request and responses as well

### ISSUE THREAD

**Issue by ashmeet-kandhari** [firecamp-io/firecamp#155]
As a user, 
It would be great if we can add beautify/minify option for structured data of type json, xml, yaml etc.

**Comment by Nishchit14** [comment]
That would be nice @ashmeet-kandhari

**Comment by pranavwani** [comment]
shipped with [v2.5.0](https://github.com/firecamp-io/firecamp/releases/tag/v2.5.0)
