### ISSUE TITLE
Graphql schema auto refresh issue

### ISSUE THREAD

**Issue by Nagendra349** [firecamp-io/firecamp#156]
HI,

We have implemented graphql framework  for backend service in our project. The service is working fine in dev and stage environments, but when we check in production systems we are getting schema auto refresh issue, the schema is not refreshed automatically. Due to the UI is not working well. can you please help me on this.

**Comment by Nishchit14** [comment]
Hi, @Nagendra349 Thank you for sharing your use case. The schema auto-refresh option is not available in Firecamp v1. We're building v2 and considering this option soon. If you hit enter in the URL bar then it'll re-fetch the schema of the given endpoint. please try it and do let me know if it's works for you or not.

**Comment by Nishchit14** [comment]
@Nagendra349 you can now click on the `Fetch Schema` button to re-fetch them, still, we'll add the auto fetch option in config in the future.

![image](https://user-images.githubusercontent.com/5078921/123069511-79af9180-d430-11eb-99f3-19366b19fe21.png)
