### ISSUE TITLE
A way to duplicate a tab with same listeners and events 

### ISSUE THREAD

**Issue by shadialtarshaold** [firecamp-io/Firecamp#16]
Hello, 
First thanks for Firecamp extension to test realtime application. It is really helpful. I am using the tool to test a chat room system, so I need at least two tabs open (for two clients), so when I added a new tab, I needed to add every listeners, and events that the first tab (client) had. It would be great if there is a way to do that without the need to rewrite everything again.

**Comment by mrhammadasif** [comment]
Really, how could we even test multi-user (multiple clients) socket.io testing without duplicating?

**Comment by Nishchit14** [comment]
@shadialtarsha Thanks for sharing the use-case, This feature is in our roadmap now. will keep you updated. 

@mrhammadasif you can open two request-tabs and connect to same server URL (each connects will behave like a new client).

**Comment by Nishchit14** [comment]
[Firecamp v2.0](https://github.com/firecamp-io/Firecamp/releases/tag/v2.0.0) released. you can now create multiple connections in the same tab.
