### ISSUE TITLE
Can't resolve host name of "localhost" in v.2.0.5 Windows 10

### ISSUE THREAD

**Issue by ksiotis** [firecamp-io/Firecamp#162]
**Describe the bug**
I cannot perform requests to localhost because the host name cannot be resolved, although it used to work in previous versions.

**To Reproduce**
1. Make any request to localhost.

**Expected behavior**
The request is supposed to work (and in fact it did use to work correctly in version 1)

**Screenshots 0r Video**
the request:
![image](https://user-images.githubusercontent.com/36239726/122809656-0fcfa480-d2d7-11eb-9fc1-7321c405b60e.png)
the response:
![image](https://user-images.githubusercontent.com/36239726/122809314-9e8ff180-d2d6-11eb-95f6-5ada670cf309.png)

**Platform (please complete the following information):**
 - Type:  Desktop
 - OS: Windows 10
 - Firecamp Version: 2.0.5

**Temporary Solution**
It was fixed by manually adding a rule in the hosts file of windows.

**Comment by Nishchit14** [comment]
Thank you @ksiotis for sharing, please use `127.0.0.1` instead of `localhost`, we'll fix them in the coming patch release.

**Comment by Nishchit14** [comment]
The issue is fixed... will be shipped in the coming release. [read this thread for more detail.](https://github.com/JCMais/node-libcurl/issues/280)

**Comment by Nishchit14** [comment]
Thank you @ksiotis for sharing it. It's now released https://github.com/firecamp-io/Firecamp/releases/tag/v2.0.11
