### ISSUE TITLE
couldn't connect to server (Error code: 7)

### ISSUE THREAD

**Issue by danieldflrs** [firecamp-io/Firecamp#163]
![Captura de pantalla 2021-06-30 122926](https://user-images.githubusercontent.com/83986091/124012846-d534ce80-d99e-11eb-9809-62c98184dda6.png)
this happens when trying to connect, but my server is running
 On windows 10 wsl2

**Comment by Nishchit14** [comment]
@danieldflrs It happens when the server is not started yet. are you sure that the local server is running on port `3000`

**Comment by Nishchit14** [comment]
released https://github.com/firecamp-io/Firecamp/releases/tag/v2.0.11
----
@danieldflrs If you still face this issue, feel free to reopen this thread.

**Comment by ngimdock** [comment]
I have the same problem with firecamp, My server is running but when I make requests it throw me the same error than @Nishchit14. How can i fix this please

**Comment by ngimdock** [comment]
need help please

**Comment by shreya-gr** [comment]
@ngimdock are you sure the server is running? can you please share the result of `curl htttp://localhost:3000` from terminal? please set the port of your server instead of `3000`

**Comment by ngimdock** [comment]
Thanks for your answer @shreya-gr 

Yes my server is running, i am using postman and it work properly but when i use firecamp for making request it throw me that error

This is the output when i make request on port 3000:

on firecamp
![image](https://i.ibb.co/5Y6g5z4/firecamp-error.png)

on the terminal
![image terminale](https://i.ibb.co/2PtnMm3/response.png)

This is the output when i change the port and making request on port 8000:

on firecamp
![image 2](https://i.ibb.co/GMMWCrx/firecamp2.png)

on the terminal
![image 4](https://i.ibb.co/ZSQqrQg/terminal-answer.png)

**Comment by ngimdock** [comment]
the only time I used fire and everything worked fine was the day of the installation. The rest of the times I got this error.

**Comment by Nishchit14** [comment]
@ngimdock please try with `http:` protocol

**Comment by ngimdock** [comment]
Yes @Nishchit14  while creating the request, i setup the `request type` to `http` but i have the same issue.

**Comment by Nishchit14** [comment]
you have entered the wrong URL pattern, try `http://localhosr:3000/auth/login` instead of `localhost//:3000/`

<img width="573" alt="image" src="https://user-images.githubusercontent.com/5078921/209055414-c489a11c-bcc0-403e-b7ae-3a2c603051f3.png">
