### ISSUE TITLE
Imports only one parameter

### ISSUE THREAD

**Issue by vlad-qa-auto** [firecamp-io/Firecamp#167]
Import imports only the last query parameter from Json.

#### 2. To Reproduce
1. Import Json with request with several query parameters, like
{"paths": {"/api/end": {
            "get": {
                "parameters": [
                    {
                        "name": "param1",
                        "in": "query",
                        "required": false,
                        "type": "integer",
                        "format": "int32"
                    },
                    {
                        "name": "param2",
                        "in": "query",
                        "required": false,
                        "type": "array",
                        "items": {
                            "type": "integer",
                            "format": "int32"
                        },
                        "collectionFormat": "multi"
                    }]}}}

Will be imported the request /api/end with only one parameter param2

-----

 - Firecamp Version: v2.0.10
 - Type: Desktop
 - OS: Win 10

**Comment by Nishchit14** [comment]
@vlad-qa-auto May I know which format/file you're importing in Firecamp? the JSON snippet you've shared seems unknown format to me. Is it JSON schema?

**Comment by vlad-qa-auto** [comment]
@Nishchit14, it's a part of my huge Json from Swagger

**Comment by Nishchit14** [comment]
please try now @vlad-qa-auto , It's fixed now. Thank you for sharing it.
released https://github.com/firecamp-io/Firecamp/releases/tag/v2.0.11
