### ISSUE TITLE
[Cookie] clear all cookie issue

### ISSUE THREAD

**Issue by shreya-gr** [firecamp-io/Firecamp#170]
#### 2. To Reproduce
1. Go to 'Cookie manager'
2. add a few cookies
3. Try to clear all cookies.

#### 4. Additional context
anything you want to share additially.

-----

##### Platform (please complete the following information):
 - Firecamp Version: v2.0.10
 - Type: Desktop
 - OS: Mac

**Comment by Nishchit14** [comment]
released https://github.com/firecamp-io/Firecamp/releases/tag/v2.0.11
