### ISSUE TITLE
renaming request with special character

### ISSUE THREAD

**Issue by Nishchit14** [firecamp-io/firecamp#173]
#### 1. Describe the bug, what it is and what it should be (expected behavior)
 I could rename the request with words like ç ã and on this version, I can't. (reported by Francisco)

#### 2. To Reproduce
1. try to rename a request with `ç ã` characters

-----

##### Platform (please complete the following information):
 - Firecamp Version: v2.0.11
 - Type: Desktop/Web/Chrome Extension
 - OS: Mac/Linux/Win

**Comment by pranavwani** [comment]
Fixed and shipped with `v2.4.2`
