### ISSUE TITLE
JSON payload on chatboard differs from one sent to server (RAW vs JS Obj)

### ISSUE THREAD

**Issue by iansmathew** [firecamp-io/Firecamp#18]
The chatboard displays the JSON payload as it was entered in the text box. However, the actual payload sent to the server is a JS object. This throws an `unexpected token` error server-side when the server expects a stringify-ed or raw JSON and parses it. 

## Expected Behavior

The payload should be sent as the sent as the user has written it. This allows the dev to test for multiple cases of incorrect payload requests. Any cleaning up or transformation in the middle removes the ability for the dev to respond to these issues. 

## Current Behavior
The payload (_written as a JSON object_) is transformed and sent to the server as a JavaScript object. 
A `JSON.parse()` on the incoming payload will result in an error.

## Possible Solution
Allow the user to chose between sending raw payload and transformed payload.

## Steps to Reproduce

1. Enter a JSON object in the text field. Eg: `{"UserID": "TestUser"}`
1. `console.log` the raw payload server-side.
1. The output is as follows: `{ UserID: 'TestUser' }`
1. The chatboard output however is of `{"UserID": "TestUser"}`

**Comment by Nishchit14** [comment]
[Firecamp v2.0](https://github.com/firecamp-io/Firecamp/releases/tag/v2.0.0) released.
