### ISSUE TITLE
[feature request]cookie is not being parsed when url's host is defined as variable

### ISSUE THREAD

**Issue by Nishchit14** [firecamp-io/firecamp#182]
#### 1. Describe the bug, what it is and what it should be (expected behavior)
when an URL is defined as a variable at that time cookie is not being parsed, for example, if the URL is `{{host}}` where the `host` value is `https://google.com` then the cookie is not being parsed to send them in request.

If URL is is a raw string like `https://google.com` then everything is working fine.

#### 2. To Reproduce
steps to reproduce the behavior:
1. go to the URL bar
2. type {{host}} and set host variable value as any endpoint which is live and contains a cookie
3. execute the request or other API which is starting with `{{host}}/...`
4. check the cookie is being sent in a request or not.

-----

##### platform (please complete the following information):
 - firecamp version: v2.2.0
 - type: desktop
 - os: mac/linux/win

**Comment by Nishchit14** [comment]
released [v2.2.1](https://github.com/firecamp-io/firecamp/releases/tag/v2.2.1)

**Comment by theigwe** [comment]
@Nishchit14 

This issue persists on localhost.
Also, at my end, the url being a variable has no impact.
