### ISSUE TITLE
[user-feedback] socket.io GUI runtime enhancement 

### ISSUE THREAD

**Issue by Nishchit14** [firecamp-io/firecamp#183]
### 1. listeners duplicates on reconnection
It is being observed that when socket auto disconnects and auto-reconnect at that time the active listeners are being listened to multiple times in some cases. due to it, the same events are showing multiple times in the event logs panel. this behavior needs to be improved.
- [x] reproduce the behavior
- [x] solve the issue 

### 2. allow listeners to listen on connection
right now if the user opens the request then the user has to connect the endpoint manually and then has to click on the listeners' buttons/switches. which is being a bit of manual work. we can improve it by giving the option of auto-listen to listeners on the successful connection made.
- [x] implement this feature 

### 3. numbers and boolean values not showing
this behavior is odd in some cases that numbers and boolean values are not showing properly, we can improve it in Firecamp.
- [x] nee to reproduce it
- [x] implemented or fix it

### 4. json string format not maintain
In normal cases, It seems like working fine, but in some advance and unusual cases, It's been observed that the JSON string is not consistent in formating.
- [x] need help from the users/OP
- [x] need to reproduce it
- [x] implement and fix it
- [x] json string formating issue in log panel

--- 
analyzed from the user feedback in Discord, https://discord.com/channels/666925283571400704/826865461429141585/893084030340309022

**Comment by Nishchit14** [comment]
point 1,3 and 4 are released under [v2.2.1](https://github.com/firecamp-io/firecamp/releases/tag/v2.2.1)

**Comment by pranavwani** [comment]
released under v2.4.0
