### ISSUE TITLE
Previous response is rendered after clearing message log

### ISSUE THREAD

**Issue by pavlikm** [firecamp-io/firecamp#185]
#### 2. To Reproduce
steps to reproduce the behavior:
1. Make emit, see response (img 1)
2. clear communication (img2)
3. make different emit
4. previous response is showing (img3)
5. for correct response must select particullar message (img4). This behavior is confusing. After clear message log and make new emit, response area should be empty.

#### 3. screenshots/gif/video?
img1:
![image](https://user-images.githubusercontent.com/78898602/136217536-866111d8-f9ef-4fd8-862d-45b248dd6177.png)
img2:
<img width="961" alt="Snímka obrazovky 2021-10-06 155952" src="https://user-images.githubusercontent.com/78898602/136217718-78d1a22b-ef81-4f18-8253-9e1dba76daf3.png">
img3:
![image](https://user-images.githubusercontent.com/78898602/136217987-86078d79-6cc4-4d65-905a-caed883eb6ff.png)
img4:
![image](https://user-images.githubusercontent.com/78898602/136218294-73223e1b-b5d2-4734-9306-1d718eb9cfba.png)

#### 4. additional context
anything you want to share additionally.

-----

##### platform (please complete the following information):
 - firecamp version: v2.2.1
 - type: desktop
 - os: win

**Comment by pranavwani** [comment]
Fixed and shipped with `v2.4.2`
