### ISSUE TITLE
socket.io: multiple listeners not re-subscribe on socket reconnect

### ISSUE THREAD

**Issue by pranavwani** [firecamp-io/firecamp#190]
#### 1. Describe the bug, what it is and what it should be (expected behavior)
On socket reconnect, listeners do not re-subscribe need to re-subscribe manually all listeners. where already showing listen on in UI. This happens when the request has multiple listeners with a single listener that works fine. 

#### 2. To Reproduce
steps to reproduce the behavior:
1. create a request with multiple listeners
2. connect with the socket server
3. listen on multiple listeners (require to test)
4. try to re-connect the socket connection
5. and try emitting multiple listeners  

##### platform (please complete the following information):
 - firecamp version: v2.3.1
 - type: desktop
 - os: mac/linux/win

**Comment by evanholt1** [comment]
i also faced this issue.
in the newest version, listeners do not trigger, unless i first set the listeners to off, then back to on. 

firecamp version 2.3.1
type: desktop
os: win

**Comment by pranavwani** [comment]
Hi, @evanholt1 issue will be fixed in the upcoming release. this issue exists in the desktop app. In the chrome extension, it's working fine may it help until the next release.

**Comment by pranavwani** [comment]
@evanholt1 issue fixed and was shipped with canary version directly download from [#here](https://firecamp.io/download). in production will be shipped soon.

**Comment by pranavwani** [comment]
@evanholt1 issue fixed and shipped in windows production `v2.3.4`. You can download from [here](https://firecamp.io/download/)
