### ISSUE TITLE
do not resend get parameters in oauth

### ISSUE THREAD

**Issue by pavlikm** [firecamp-io/firecamp#196]
#### 1. Describe the bug, what it is and what it should be (expected behavior)
any GET param from Auth URL is discarded

#### 2. To Reproduce
1. add some GET param to Auth URL (img1)
2. after click on Fetch Token, request to Auth URL is made without GET param (img2 shows forbiden resource, because api_key was not send)

#### 3. screenshots/gif/video?
<img width="344" alt="img1" src="https://user-images.githubusercontent.com/78898602/149523182-a074651e-b182-4a8f-81ad-41bd32b98a7c.png">
<img width="432" alt="img2" src="https://user-images.githubusercontent.com/78898602/149523193-edaf2715-fba3-424c-b92d-3d85788c0ff1.png">

-----

##### platform (please complete the following information):
 - firecamp version: v2.4.2
 - type: desktop
 - os: win

**Comment by pranavwani** [comment]
@pavlikm issue was fixed and shipped with Firecamp canary v2.5.0-canary.1.

You can download from [#here](https://firecamp.netlify.app/.netlify/functions/download?env=canary&pt=win)

**Comment by pranavwani** [comment]
The Issue was fixed and shipped with Firecamp v2.5.0.

**Comment by pranavwani** [comment]
the issue was fixed and shipped with [v2.5.0](https://github.com/firecamp-io/firecamp/releases/tag/v2.5.0)
