### ISSUE TITLE
Inactuall value for {{$timestamp}} 

### ISSUE THREAD

**Issue by pavlikm** [firecamp-io/firecamp#197]
#### 1. Describe the bug, what it is and what it should be (expected behavior)
When use {{$timestamp}} value, firecamp will use timestamp which is not actual, but time when app starts in each request.

#### 2. To Reproduce
steps to reproduce the behavior:
1. try to send repeatly request as shown on img
2. in message log (img) is same time for every call, but should be unique for each call
3. in message log (img) can see, that this timestamp is not actual. After close and reopen app, this value will be changed to time, when app was opened

#### 3. screenshots/gif/video?
<img width="739" alt="img" src="https://user-images.githubusercontent.com/78898602/151382272-f79dff73-0347-4711-a9f1-e3f5043cf12b.png">

-----

##### platform (please complete the following information):
 - firecamp version: nsis-v2.5.1
 - type: desktop
 - os: win

**Comment by pranavwani** [comment]
@pavlikm the issue was fixed and shipped with v2.5.2

**Comment by pavlikm** [comment]
@pranavwani  can't try, because release 2.5.2 not working for me :( With this version I can't even connect to my ws, because header auth is not sent. Check this issue: https://github.com/firecamp-io/firecamp/issues/198
Is there any possibility to download previous working release?

**Comment by pranavwani** [comment]
@pavlikm please check the [#comment ](https://github.com/firecamp-io/firecamp/issues/198#issuecomment-1025584630) may fix the issue

**Comment by pavlikm** [comment]
thanks @pranavwani. So, I can confirm, that this issue is resolved in 2.5.2 👍
