### ISSUE TITLE
Auth header is not sent 

### ISSUE THREAD

**Issue by pavlikm** [firecamp-io/firecamp#198]
#### 1. Describe the bug, what it is and what it should be (expected behavior)
Auth header for socket.io is not sent

#### 2. To Reproduce
steps to reproduce the behavior:
1. After sending some access token in auth for socketio, this token is not sent to server
2. in console.log(client.headers) is auth empty object

#### 3. screenshots/gif/video?
![image](https://user-images.githubusercontent.com/78898602/151768775-d99ddebe-9537-42c0-a90e-ff80c0231e5a.png)
<img width="580" alt="bug-no-auth" src="https://user-images.githubusercontent.com/78898602/151768688-0d127c6d-97cc-4eed-a2d3-ef506202752a.png">

-----

##### platform (please complete the following information):
 - firecamp version: v2.5.2 (in 2.5.0 it works)
 - type: desktop
 - os: win

**Comment by pranavwani** [comment]
@pavlikm can you please confirm, in the screenshot auth entry checkbox is unchecked in the first column may be that cause auth is not passing.

![Screenshot from 2022-01-31 15-52-21](https://user-images.githubusercontent.com/26399261/151776752-4a739c1f-d599-40fa-b1c0-19f222426fa8.png)

**Comment by pavlikm** [comment]
@pranavwani damn, my fault 😶 sorry for false alarm, I do not understand how and when I unchecked it 👽

**Comment by pranavwani** [comment]
@pavlikm no worry just save the request after updating the config and feel free to raise the issue
