### ISSUE TITLE
SocketIO emits without payload are broken

### ISSUE THREAD

**Issue by victorvorobev** [firecamp-io/firecamp#199]
#### 1. Describe the bug, what it is and what it should be (expected behavior)

There is no "Send" button, if I pick "No body" option for argument, however, it's there for any other option.

#### 2. To Reproduce
- Create new Socket IO request (by the way, there is no SIO option in quick access drop-down list)
- Set "no body" option

#### 3. screenshots/gif/video?
"No body" - no button
![image](https://user-images.githubusercontent.com/19344219/151775494-e05f0b26-a10d-4e2f-92e8-248f8987431f.png)

"JSON" - there is button
![image](https://user-images.githubusercontent.com/19344219/151775525-011272b6-7273-47e3-a12d-be7c67dae1ef.png)

#### 4. additional context
anything you want to share additionally.

-----

##### platform (please complete the following information):
 - firecamp version: v2.5.1
 - type: desktop
 - os: linux

**Comment by pranavwani** [comment]
Thanks, @victorvorobev for raising the issue. It will be fixed soon

**Comment by pranavwani** [comment]
@victorvorobev issue was fixed and shipped in the canary version. feel free to share your feedback

**Comment by pranavwani** [comment]
The issue was fixed and shipped in the prod. [v2.6.0](https://github.com/firecamp-io/firecamp/releases/tag/v2.6.0)
