### ISSUE TITLE
[Feature Request] Add button in UI to open the console

### ISSUE THREAD

**Issue by DanTalash** [firecamp-io/firecamp#201]
The console is not very discoverable since it can only be opened via keyboard shortcut, the shortcuts are not the standard (F12), and the keyboard shortcut to open it isn't really mentioned anywhere in the UI or the docs. 

There should ideally be a button in the UI for opening the console, maybe somewhere in the bottom panel?

**Comment by pranavwani** [comment]
@DanTalash now can open dev tool from the app menu added and shipped with [v2.6.0](Exceptions do not get logged in the console, or otherwise shown https://github.com/firecamp-io/firecamp/issues/203 @DanTalash)
