### ISSUE TITLE
Scrollbar in editor is difficult to use

### ISSUE THREAD

**Issue by DanTalash** [firecamp-io/firecamp#202]
The scrollbar in the code editor has a clickable area which is very small, only one pixel wide. It's difficult to use, and it would be great if there were an option to make the scrollbar wider. The clickable area to resize the panels is huge, but that task would be done less frequently by users than navigating through their code.

See below zoomed in recording. The cursor is mostly in panel resizing mode, with one single pixel in the middle devoted to actually using the scrollbar.

![firecamp-scrollbar](https://user-images.githubusercontent.com/3004715/154538441-a3364d65-2309-4907-ad93-f1800761bb46.gif)

**Comment by pranavwani** [comment]
The issue was fixed and shipped in prod. [v2.6.0](https://github.com/firecamp-io/firecamp/releases/tag/v2.6.0)
