### ISSUE TITLE
Exceptions do not get logged in the console, or otherwise shown

### ISSUE THREAD

**Issue by DanTalash** [firecamp-io/firecamp#203]
#### 1. Describe the bug, what it is and what it should be (expected behavior)
When a test script generates any kind of exception, it is silently ignored and the rest of the script does not execute without indication of this.

#### 2. To Reproduce
steps to reproduce the behavior:
1. Create a test.
2. Add a pre-test script which is invalid, such as the following:
```
var someObj;

someObj.nonExistentFunction();
```
3. Run the test. Even though that code threw an error, no indication of this shows up in the console or anywhere else in the UI.

-----

##### platform:
 - firecamp version: v2.5.2
 - type: desktop
 - os: windows 10

**Comment by pranavwani** [comment]
@DanTalash now can open dev tool from the app menu added and shipped with [v2.6.0](Exceptions do not get logged in the console, or otherwise shown https://github.com/firecamp-io/firecamp/issues/203 @DanTalash)
