### ISSUE TITLE
When i open saved project all listeners should be selected by default. (Socket.io)

### ISSUE THREAD

**Issue by suraj-26p** [firecamp-io/firecamp#22]
When i open saved project all listeners should be selected by default.

**Comment by Nishchit14** [comment]
shipped with [v2.4.0](https://github.com/firecamp-io/firecamp-oss/releases/tag/v2.4.0)

You can add listeners to be listened default on connection happens. You can find the `ON CONNECT LISTENERS` option in the config tab.
