### ISSUE TITLE
Request gets deleted after authentication

### ISSUE THREAD

**Issue by qweryty** [firecamp-io/firecamp#221]
#### 1. Describe the bug, what it is and what it should be (expected behavior)
Title is self-explanatory

#### 2. To Reproduce
steps to reproduce the behavior:
1. Open an app
2. Create a request(I tried with websocket request)
3. Sign in
4. No requests open

#### 3. screenshots/gif/video?
-

#### 4. additional context
-

-----

##### platform (please complete the following information):
 - firecamp version: v2.7.1
 - type: desktop
 - os: linux

**Comment by Nishchit14** [comment]
You might be using very very old version. In latest version It's not allowed to save the request without being sign into account.
