### ISSUE TITLE
update on AUR

### ISSUE THREAD

**Issue by MA-Mahmudi** [firecamp-io/firecamp#227]
Why don't you update the package on AUR, is there any problem? Could you please update Firecamp on AUR to the latest version? The package is out-of-date and there is no other way to install and use it on Arch linux. (Appimage won't work.)

**Comment by pranavwani** [comment]
Hi @MA-Mahmudi,

can you please check with snap-store. using snap store you can install Firecamp easily by command: `snap install firecamp`

**Comment by MA-Mahmudi** [comment]
Hello again.

Previously I had Ubuntu installed on my desktop and because of Snap bugs I had to change my OS.
Actually I just don't want to risk my data again by installing Fire camp via Snap.

**Comment by pranavwani** [comment]
May be @Nishchit14 can help with this one

**Comment by Nishchit14** [comment]
@MA-Mahmudi which version do you have right now?

**Comment by MA-Mahmudi** [comment]
If you mean Firecamp, I don't have it at all!
