### ISSUE TITLE
Feature Request: Option to allow self-signed certificates.

### ISSUE THREAD

**Issue by sbrow** [firecamp-io/Firecamp#29]
Currently, it is not possible to connect to a socket.io server over https if the server uses a self-signed certificate. Having the option to toggle this behavior would be nice.

**Comment by sbrow** [comment]
On second thought, if you expose the connection options to the ui, users could do this themselves via:
```js
const socket = io("https://<some endpoint>", {rejectUnauthorized: false});
```

**Comment by Nishchit14** [comment]
[Firecamp v2.0](https://github.com/firecamp-io/Firecamp/releases/tag/v2.0.0) released.
