### ISSUE TITLE
Listener event-based filter

### ISSUE THREAD

**Issue by priyank6796** [firecamp-io/firecamp#3]
You might add a listener event-based filter. If the user wants to show a message from a particular event. 
Example - User is testing chat application(socket.io server) using this tool. he adds two listeners. one for a new message and another for typing event. it is getting a message from both the listener. If a user wants to show messages from one event only.

**Comment by pranavwani** [comment]
The feature to filter logs according to the event and log type shipped with [v2.6.0](https://github.com/firecamp-io/firecamp/releases/tag/v2.6.0#:~:text=Filter%20connection%20logs%20(SocketIO/WS%20requests))
