### ISSUE TITLE
Feature Request: Comments on socket args 

### ISSUE THREAD

**Issue by Kalmuraee** [firecamp-io/firecamp#31]
It would be very helpful If we are able to have comments 

<img width="736" alt="Screen Shot 2019-10-13 at 11 25 02 AM" src="https://user-images.githubusercontent.com/7072748/66712888-4b009d00-edac-11e9-9528-2ab1c021f3ad.png">

**Comment by pranavwani** [comment]
@Kalmuraee feature to store example of emitter and listener will help

**Comment by pranavwani** [comment]
shipped with [v2.5.0](https://github.com/firecamp-io/firecamp/releases/tag/v2.5.0)
