### ISSUE TITLE
Manual refresh button/utility to fetch introspection schema

### ISSUE THREAD

**Issue by Nishchit14** [firecamp-io/Firecamp#40]
Can you add any button to re-fetch graphql schema? Because in development mode my server change many time and I have to close and open Firecamp again. 

![image](https://user-images.githubusercontent.com/5078921/70894095-583b4180-2012-11ea-90cc-ba8e9c002b18.png)

reported by - Hienlh

**Comment by dwthien** [comment]
yeah, I think so, I have to close and open again to fetch schema

**Comment by Nishchit14** [comment]
[Firecamp v2.0](https://github.com/firecamp-io/Firecamp/releases/tag/v2.0.0) released.
