### ISSUE TITLE
[Socket.io] Shows only first argument of acknowledgements

### ISSUE THREAD

**Issue by ttrubel** [firecamp-io/Firecamp#46]
```
socket.emit('some.event', { test: true }, (err: Error, data: any) => {
  if (err) { // null if no errors
    console.error('error', err);
  }

  console.log('data', data);
});
```

<img width="262" alt="Снимок экрана 2020-01-21 в 14 15 27" src="https://user-images.githubusercontent.com/6205636/72792993-b4216780-3c5b-11ea-81ad-eeb03736f3e4.png">

We see only `null`, but there is `data` as second argument. 

Looks like message shows only first argument of ack

**Comment by Nishchit14** [comment]
This is interesting, Thanks for creating this issue 👏

**Comment by Nishchit14** [comment]
[Firecamp v2.0](https://github.com/firecamp-io/Firecamp/releases/tag/v2.0.0) released.
