### ISSUE TITLE
Optional Sec-WebSocket-Extensions and extension parameters

### ISSUE THREAD

**Issue by pavelsaman** [firecamp-io/Firecamp#55]
In WebScokets, a user can choose custom subprotocols:
![image](https://user-images.githubusercontent.com/24702416/73679795-6aa13580-46bb-11ea-9383-453d975c0d49.png)

I'd be nice if `Sec-WebSocket-Extensions` could be chosen as well since the header is optional and doesn't need to be sent with a client's request at all. Currently, Firecamp wants to use extension `permessage-deflate` with parameter `client_max_window_bits`, and it doesn't seem that either one can be changed (e.g. disabled, so Firecamp doesn't send it in the opening handshake).

![image](https://user-images.githubusercontent.com/24702416/73680579-c91ae380-46bc-11ea-9601-852ce938b1dc.png)

Firecamp v0.9.2

**Comment by Nishchit14** [comment]
Released under [v1.4.0](https://github.com/firecampapp/Firecamp/releases/tag/1.4.0) (via Headers)

Todo: Provide a dedicated config option

**Comment by Nishchit14** [comment]
[Firecamp v2.0](https://github.com/firecamp-io/Firecamp/releases/tag/v2.0.0) released.
