### ISSUE TITLE
Firecamp logo interfering in emmitters tab

### ISSUE THREAD

**Issue by tusharlock10** [firecamp-io/Firecamp#67]
I am trying to select a response to emit, but the firecamp logo at the bottom right, gets in my way. I have to take my mouse to the very correct spot to emit messages. Can this be fixed in the next release
![Untitled](https://user-images.githubusercontent.com/36128584/74100338-e08e1c80-4b53-11ea-9fc6-3252a4c63cb7.png)

**Comment by Nishchit14** [comment]
[Firecamp v2.0](https://github.com/firecamp-io/Firecamp/releases/tag/v2.0.0) released.
