### ISSUE TITLE
Sample JSON for default event data tab

### ISSUE THREAD

**Issue by priyank6796** [firecamp-io/Firecamp#7]
There isn't have sample JSON for default event data tab. When I create a new tab. It displays sample JSON as shown in attached GIF. It is not a big issue. Just for improving UX more. 
![firecamp_1](https://user-images.githubusercontent.com/17333370/50589708-b1679f00-0ead-11e9-86f8-ef7a34f21f2f.gif)

**Comment by Nishchit14** [comment]
[Firecamp v2.0](https://github.com/firecamp-io/Firecamp/releases/tag/v2.0.0) released.
