### ISSUE TITLE
Cursor appears at the beginning of a line even when (sub)points are automatically added

### ISSUE THREAD

**Issue by pavelsaman** [firecamp-io/Firecamp#74]
1. problem

In markdown, there's a feature when points and numbers in lists are automatically added when [Return] is pressed (when moving to a new line). However, this doesn't work well with the fact that the cursor is always set at the beginning of a line.

![markdown_list_handling](https://user-images.githubusercontent.com/24702416/74372307-b39f6b00-4dda-11ea-9e78-19f117aa01f3.gif)

2. steps to reproduce

markdown => create a list, it can be both a numbered list, or with (sub)points => hit [Return]

3. desired behaviour

When automatically adding "-" or numbers as part of a (numbered) list, set the cursor at the end of such a line.

4. version

Snap v1.0.0

**Comment by Nishchit14** [comment]
[Firecamp v2.0](https://github.com/firecamp-io/Firecamp/releases/tag/v2.0.0) released.
