### ISSUE TITLE
Add an option to manage cookies

### ISSUE THREAD

**Issue by pavelsaman** [firecamp-io/Firecamp#80]
At present, I don't see an option to manage cookies in API. It has two implications:

1. If I get some cookies in a response, I can't delete them, so with every other related request, the cookies are sent as well.
2. I can't set cookies at will.

I've also tried to close a tab or close Firecamp completely, but stored cookies are remembered and used the next time on related requests.

**Comment by Nishchit14** [comment]
[Firecamp v2.0](https://github.com/firecamp-io/Firecamp/releases/tag/v2.0.0) released.
