### ISSUE TITLE
Allow developer tools?

### ISSUE THREAD

**Issue by shirshak55** [firecamp-io/firecamp#84]
I think this use electron right? So how about allowing developer tools. Discord and many other popular software already provides electron so it would be better for debugging some stuff.

**Comment by iangregsondev** [comment]
Yes, i agree here, or some way of seeing the request / responses (raw) going out. 

Actually not just for HTTP but also for websockets. I think these are all do-able in chrome dev tools.

What probably is not is when we get other things added like NATS, MQTT, ZEROMQ etc. i dont thing these would show up inside the chrome dev tools so it would be nice to show some additional custom debug panel inside the application.

**Comment by Nishchit14** [comment]
It's in our plan and will give it's access soon, ETA would be 2week.

**Comment by pranavwani** [comment]
Option to access dev tool added in [v2.6.0 ](https://github.com/firecamp-io/firecamp/releases/tag/v2.6.0#:~:text=%5BFeature%20Request%5D%20Add%20button%20in%20UI%20to%20open%20the%20console)
