### ISSUE TITLE
Please change the Firecamp repo thumbnail images 

### ISSUE THREAD

**Issue by shreya-gr** [firecamp-io/Firecamp#95]
@Nishchit14 please change the thumbnail image for Firecamp repo as per the direction in this [link](https://help.github.com/en/github/administering-a-repository/customizing-your-repositorys-social-media-preview)
Use the image from Firecamp intro.

**Comment by Nishchit14** [comment]
[Firecamp v2.0](https://github.com/firecamp-io/Firecamp/releases/tag/v2.0.0) released.
